% my_plot({'theta_m', 'v_q'}, 'color', {'b', 'r'}, 'layout', 'subplotV', 'lineWidth', [2, 1.5], 'lineStyle', {'-', '--'}, 'title', {'Gráfico de Theta', 'Gráfico de Velocidad'}, 'ylabel', 'theta');
% OPCIONES
% 'layout','subplotV' para graficar subplots verticales
% 'layout','subplotH' para graficar suplots horizontales
% 'layout'.'unico' para graficar todo en un solo grafico
clc;
my_plot_simulink({'delta', 'delta_ref'}, ...
    'color', {'b','r'}, ...
    'layout', 'unico', ...
    'lineStyle', {'-', '--'},...
    'lineWidth', [1.5],...
    'title', {'Referencia escalón 10° - Con perturbación T_a'},...
    'ylabel', 'delta');

my_plot_simulink({'Vm'}, ...
    'color', {'m'}, ...
    'layout', 'unico', ...
    'lineStyle', {'-'},...
    'lineWidth', [1.5],...
    'title', {'Referencia escalón 30°'},...
    'ylabel', 'Vm');

my_plot_simulink({'im'}, ...
    'color', {'g'}, ...
    'layout', 'unico', ...
    'lineStyle', {'-'},...
    'lineWidth', [1.5],...
    'title', {'Referencia escalón 10°'},...
    'ylabel', 'im');
